name: divergent
description: Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  another_flutter_splash_screen: ^1.2.0
  avatar_glow: ^3.0.1
  camera: ^0.11.0+1
  colornames: ^0.1.0
  connectivity_plus: ^6.0.3
  device_info_plus: ^10.1.0
  easy_splash_screen: ^1.0.4
  english_words: ^4.0.0
  eva_icons_flutter: ^3.1.0
  firebase_core: ^3.0.0
  firebase_ml_model_downloader: ^0.3.0
  flutter_tesseract_ocr: ^0.4.24
  flutter_tflite: ^1.0.1
  flutter_tts: ^4.0.2
  fluttertoast: ^8.2.6
  geolocator: ^12.0.0
  hexcolor: ^3.0.1
  highlight_text: ^1.7.0
  http: ^1.2.1
  image: ^3.3.0
  image_picker: ^0.8.9
  palette_generator: ^0.3.3+3
  path: ^1.9.0
  path_provider: ^2.1.3
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
#  sensors_plus: ^1.4.1 #
  shake: ^2.2.0
  shared_preferences: ^2.2.3
  speech_to_text: ^6.6.0
  sqflite: ^2.3.3+1
  telephony: ^0.2.0
  # tflite_flutter: ^0.10.4
  vibration: ^1.9.0


  # english_words: ^4.0.0
  # flutter_tts: ^4.0.2
  # hexcolor: ^3.0.1
  # another_flutter_splash_screen: ^1.2.0
  # image_picker: ^1.0.7
  # eva_icons_flutter: ^3.1.0

  # http: ^1.2.0
  # path: ^1.8.3
  # shared_preferences: ^2.2.2
  # shake: ^2.2.0
  # telephony: ^0.2.0
  # fluttertoast: ^8.2.4
  # geolocator: ^11.0.0
  # vibration: ^1.8.4
  # percent_indicator: ^4.2.3
  # animated_splash_screen: ^1.3.0
  # colornames: ^0.1.0
  # firebase_ml_model_downloader: ^0.3.0
  # # The following adds the Cupertino Icons font to your application.
  # # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.6
  # path_provider: ^2.1.2
  # avatar_glow: ^3.0.1
  # highlight_text: ^1.7.0
  # speech_to_text: ^6.5.1
  # sqflite: ^2.3.0
  # easy_splash_screen: ^1.0.4
  # connectivity_plus: ^6.0.1
  # device_info_plus:
  # permission_handler: ^11.3.0
  # flutter_tflite: ^1.0.1
  # # tflite: ^1.0.3
  # palette_generator: ^0.3.3+3
  # tflite_flutter: ^0.10.4
  # #starflut: ^1.0.0
  # camera: any
  # image: any
  # sensors_plus: ^1.4.1
  # flutter_tesseract_ocr: ^0.4.24
  # firebase_core: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/
    - assets/model.tflite
    - assets/ssd_mobilenet.tflite
    - assets/ssd_mobilenet.txt
    - assets/cash_model_unquant.tflite
    - assets/cash_labels.txt
    - assets/Aeye.png
    - assets/icon-circle.png
    - assets/model_unquant_cash.tflite
    - assets/labels_cash.txt
    - assets/tflite/model_unquant.tflite
    - assets/tessdata_config.json
    - assets/tessdata/eng.traineddata
    - assets/images/

flutter_icons:
  image_path: 'assets/Aye.png'
  android: true
  ios: true